[project]
name = "example-project"
version = "0.1.0"
description = "Fixture to test ManifestUpdater.update_toml"

dependencies = [
  "requests==2.32.5",
  "idna==3.11",
]

[project.optional-dependencies]
test = [
  # NON-TARGET: should not be touched
  "pytest==7.4.0",
]

[tool.poetry.dependencies]
python = "^3.11"
# NON-TARGET
tomli = "2.0.1"

[build-system]
requires = [
  # TARGET: this is where pip comes from the purl pypi:pip:25.0.1
  "setuptools==82.0.0",
  "pip==26.0.1",
]
build-backend = "setuptools.build_meta"

[tool.some_other_tool]
ignore_me = true
